# Stage 1: Build com Maven + JDK 17
FROM maven:3.9.4-eclipse-temurin-17 AS build

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

# Stage 2: Runtime com JRE 17
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/workright-0.0.1-SNAPSHOT.jar app.jar

CMD ["java", "-jar", "app.jar"]
