version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_workright
    environment:
      POSTGRES_DB: workright
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789012
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - workright_net

  app:
    build: .
    container_name: spring_workright
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/workright
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456789012
    networks:
      - workright_net

volumes:
  pgdata:

networks:
  workright_net:
